Adding matplotlib-specific styling functionality
Arcadia-Science/arcadia-pycolor pull request #14
Opened 2024-05-29 00:04 UTC by mezarque

## PR checklist

- [ ] Tag the issue(s) or milestones this PR fixes (e.g. `Fixes #123, Resolves #456`).
- [ ] Describe the changes you've made.
- [ ] Describe any tests you have conducted to confirm that your changes behave as expected.
- [ ] If you've added new software dependencies, make sure that those dependencies are included in the appropriate `conda` environments.
- [ ] If you've added new functionality, make sure that the documentation is updated accordingly.
- [ ] If you encountered bugs or features that you won't address, but should be addressed eventually, create new issues for them.

(to be updated later, just testing CI right now)

2024-05-30 19:14 UTC, mertcelebi reviewed
I haven't fully reviewed the `mpl` changes, but I made a couple suggestions to start a discussion. I am not sure how much research you've done around available tools, but I would check these two tools as potential inspiration: https://github.com/raybuhr/pyplot-themes and https://github.com/lgienapp/aquarel

2024-05-30 19:14 UTC, mertcelebi commented on arcadia_pycolor/mpl.py
> +_MPL_STYLESHEET = impresources.files(mplstyles) / "arcadia_2024.mplstyle"
Otherwise, you probably could use something like this to load the file: https://github.com/lgienapp/aquarel/blob/114ba2796d2061dd0ac841c0e982ad0ae2ec0c99/aquarel/utils.py#L38

2024-05-30 19:14 UTC, mertcelebi commented on arcadia_pycolor/mplstyles/arcadia_2024.mplstyle
> +axes.prop_cycle:        cycler('color', ['5088C5', 'F28360', 'F7B846', '97CD78', '7A77AB', 'F898AE', '3B9886', 'C85152', '73B5E3', 'BAB0A8', '8A99AD', 'FFB984', 'C6E7F4', 'F8C5C1', 'F5E4BE', 'B5BEA4'
what are these colors?

2024-05-30 19:14 UTC, mertcelebi commented on arcadia_pycolor/mplstyles/arcadia_2024.mplstyle
> +figure.facecolor:                   FDF8F2      # displays figures with this color
is this the background color?

2024-05-30 19:14 UTC, mertcelebi commented on arcadia_pycolor/mplstyles/arcadia_2024.mplstyle
> +axes.prop_cycle:        cycler('color', ['5088C5', 'F28360', 'F7B846', '97CD78', '7A77AB', 'F898AE', '3B9886', 'C85152', '73B5E3', 'BAB0A8', '8A99AD', 'FFB984', 'C6E7F4', 'F8C5C1', 'F5E4BE', 'B5BEA4'
ideally these would come from the colors file

2024-05-30 22:20 UTC, mezarque commented on arcadia_pycolor/mplstyles/arcadia_2024.mplstyle
> +axes.prop_cycle:        cycler('color', ['5088C5', 'F28360', 'F7B846', '97CD78', '7A77AB', 'F898AE', '3B9886', 'C85152', '73B5E3', 'BAB0A8', '8A99AD', 'FFB984', 'C6E7F4', 'F8C5C1', 'F5E4BE', 'B5BEA4'
These are colors from the palette, just input manually. I think moving to a Python dictionary would allow us to import them instead of writing them out like this, which is preferable. I'll get on that!

2024-05-30 22:20 UTC, mezarque commented on arcadia_pycolor/mplstyles/arcadia_2024.mplstyle
> +figure.facecolor:                   FDF8F2      # displays figures with this color
Yep; also should probably be imported from the colors module instead of written out.

2024-05-30 22:21 UTC, mezarque commented on arcadia_pycolor/mpl.py
> +_MPL_STYLESHEET = impresources.files(mplstyles) / "arcadia_2024.mplstyle"
I think because there were so many parameters that needed adjusting, I used stylesheets, but I think moving to dictionaries would be better, as it keeps everything in Python and allows us to import values from other modules.

2024-05-30 22:24 UTC, mezarque commented
> I haven't fully reviewed the `mpl` changes, but I made a couple suggestions to start a discussion. I am not sure how much research you've done around available tools, but I would check these two tools as potential inspiration: https://github.com/raybuhr/pyplot-themes and https://github.com/lgienapp/aquarel

Thanks for pointing me to these! I do like how `aquarel` uses `with` to specify a context for plotting; this could save users from having to have to call `autostyle` at the end of plots. I think both packages do some of the things we need to accomplish, but not all. Configurability/ usability is also something we want to consider, since I think users may not know what changes they want to make in advance of generating a plot. Let's explore these different approaches through some user testing.

2024-05-30 22:30 UTC, mezarque commented on arcadia_pycolor/fonts.py
> +import os
I did not know about this! Let's use this instead.

2024-05-30 23:04 UTC, keithchev requested changes
As we discussed offline, I think this is actually most of the way there. Most of my comments are about naming and readability, including stuff I noticed when I tried to use this branch yesterday to style heatmap figures for the peptigate pub.

General comments:
- I think it could improve clarity of the function names in `mpl` all started with verbs. So e.g. instead of `categorical_axes` use `set_axes_style_categorical` or `set_axis_style_to_categorical`.
- It would also help to use consistent nomenclature for functions that set or adjust styles. e.g. `set_axis_style`, `set_legend_style`, etc.

2024-05-30 23:13 UTC, mezarque commented on arcadia_pycolor/mpl.py
> +def monospace_ticklabels(font: str = _MONOSPACE_FONT, axis=None):
We can change the function name for the general case (accepts any fonts) to better reflect that behavior. But I think it would be good to have a narrower use case, which doesn't accept font arguments, so that users don't have to wonder about the defaults of `set_ticklabels_font`, which by name would not obviously indicate that the font will be changed to a monospaced font.

2024-05-30 23:19 UTC, mezarque commented on arcadia_pycolor/mpl.py
> +    legend_vpacker = legend._legend_handle_box.get_children()[0]
A [VPacker](https://matplotlib.org/stable/api/offsetbox_api.html#matplotlib.offsetbox.VPacker) object sets the vertical spacing around a list of matplotlib Artists. I will double check that the object that's grabbed by this is actually a VPacker, but also am open to renaming this variable.

2024-05-30 23:25 UTC, mezarque commented on arcadia_pycolor/gradient.py
> +    def to_mpl_linear_cmap(self):
Do we want to override the `to_mpl_cmap` method of the parent class? I suppose it's not likely that someone would want to make a `Gradient` into a `ListedColormap` instead of a `LinearSegmentedColormap`, but we should affirmatively decide one way or the other.

2024-05-30 23:43 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +def monospace_ticklabels(font: str = _MONOSPACE_FONT, axis=None):
Would it make sense to have both a general function `set_ticklabels_font` that requires an axis and a font name (and doesn't provide a default) and then separately a `set_ticklabels_monospace_font` that only accepts an axis?

2024-05-31 01:39 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +                plt.register_cmap(name=palname, cmap=pal.to_mpl_cmap())
This will be even more true if we can rename `Gradient.to_mpl_linear_cmap` to `to_mpl_cmap`

2024-05-31 01:44 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +    legend_vpacker = legend._legend_handle_box.get_children()[0]
I'm so glad I asked 😵‍💫. This stuff feels so opaque/confusing that I think it'd be good to add a comment here to explain why we expect (or know?) that `legend_handle_box.get_children()[0]` is a `VPacker` object and also why that's the object into whose children we need to insert `line_area`.

2024-05-31 15:51 UTC, keithchev commented on arcadia_pycolor/gradient.py
> +    def to_mpl_linear_cmap(self):
Yeah, I would say we should override `to_mpl_cmap`, because I think we should be shielding the user from the complexity of matplotlib whenever possible (e.g. in this case the difference between `Listed` vs `LinearSegmented`). In the rare case that the user does need a ListedColormap of a gradient, I think it's okay that they have to call the matplotlib function itself.

2024-05-31 19:04 UTC, mezarque commented on arcadia_pycolor/mplstyles/arcadia_2024.mplstyle
> +figure.facecolor:                   FDF8F2      # displays figures with this color
The plots are saved with a transparent background, but this sets the background when the figure is displayed in interactive contexts, e.g. Jupyter notebooks. I think making sure that this color matches with the final style guide will be useful, to that users can see how their chosen colors match to the background.

2024-05-31 19:56 UTC, mezarque commented on arcadia_pycolor/mpl.py
> +    legend_vpacker = legend._legend_handle_box.get_children()[0]
It's a mess lmao. I've added a very verbose description of everything going on; hopefully it saves someone in the future from having to try to figure all of this out.

2024-05-31 21:46 UTC, mezarque commented on arcadia_pycolor/mpl.py
> +                plt.register_cmap(name=palname, cmap=pal.to_mpl_cmap())
done!

2024-05-31 21:46 UTC, mezarque commented on arcadia_pycolor/styles.py
> +FULL_W = (20.8333, 10.6161)
Added some comments to explain what's going on!

2024-05-31 21:48 UTC, mezarque commented
I think I addressed most of the comments above - thanks for all the feedback! My main concern with the renamings is that all of the functions are now quite verbose, which feels clunky / ugly to use. But maybe that's just the sacrifice we have to make for clarity.

Should I write tests for the functionality in this PR, or wait for another PR?

2024-05-31 22:05 UTC, mezarque commented on arcadia_pycolor/mpl.py
> +def monospace_ticklabels(font: str = _MONOSPACE_FONT, axis=None):
I've split this into two functions as recommended, with the second function being `set_ticklabel_monospaced` so that it's slightly less cumbersome to type.

2024-06-01 00:45 UTC, keithchev requested changes
Caught a few minor things but very close!

The examples are great! We should (in a later PR) make sure we write a script to programmatically generate them, so we can easily keep them up-to-date.

What happened to the tests? They seem to have disappeared from the CI workflow.

> My main concern with the renamings is that all of the functions are now quite verbose, which feels clunky / ugly to use. But maybe that's just the sacrifice we have to make for clarity.

FWIW, the names don't feel verbose to me, and I feel some verbosity is a necessary sacrifice for clarity. But I'm also perhaps not the most impartial judge 🙈

> Should I write tests for the functionality in this PR, or wait for another PR?

I would say this can wait for a later PR, since this is looking pretty close as-is.

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +SAVE_WEB = dict(dpi=72, bbox_inches="tight", pad_inches=0.41)
Yeah, I think it would be worthwhile to wrap `plt.savefig` so that we can pass in these kwargs and also set the file type, so the user doesn't have to think about this. This can be done and still allow the user to pass in kwargs for `plt.savefig` by doing s/t like this
```python
def save_figure(context="web", **savefig_kwargs):
    kwargs = SAVE_WEB if context == "web" else SAVE_PRINT
    kwargs.update(**savefig_kwargs)
    plt.savefig(**kwargs)
```

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +SAVE_WEB = dict(dpi=72, bbox_inches="tight", pad_inches=0.41)
Also would suggest a descriptive name like `SAVEFIG_KWARGS_WEB` instead of `SAVE_WEB`.

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +def set_ticklabel_monospaced(font: str = MONOSPACE_FONT, axis=None):
a lingering` font` argument that should be removed

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +def set_yticklabel_fonts(axis=None, font: str = DEFAULT_FONT):
Nit: there's only one font to set (and ditto for `set_xticklabel_fonts` and `set_ticklabel_fonts`)
```suggestion
def set_yticklabel_font(axis=None, font: str = DEFAULT_FONT):
```

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +        capitalize_yticklabels(axis)
```suggestion
    if categorical_axes == "both":
        set_axes_categorical(axis)
        capitalize_ticklabels(axis)
```

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +    # TODO: Check if there are more objects in the case of a multi-column legend.
This is v useful context/explanation!

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +    for fontpath in font_manager.findSystemFonts(fontpaths=font_folder, fontext="ttf"):
Would be good to clarify the purpose of `font_folder` here. Does it always need to be provided? Or is it intended only for rare cases where the user hasn't installed the suisse-family fonts system-wide but instead has them in some local directory?

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/mpl.py
> +            either 'x', 'y', 'both', or None
Is there additional validation that could/should be done here? It sounds like categorical axes should not be monospaced font, so we might want to check that the x- and y-axes are only either monospaced or categorical. But also feels okay to punt on this for now.

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/style_defaults.py
> +    "half_s": HALF_S,
Since these keys are the allowed values of `get_figure_dimensions`, they may need to be named something more human-readable if `get_figure_dimensions` will be part of the public API.

2024-06-01 00:45 UTC, keithchev commented on arcadia_pycolor/style_defaults.py
> +    "half_s": HALF_S,
Also, in either case, I would avoid the single-letter abbreviations "W" and "S", since it's hard to infer what they stand for.

2024-06-03 21:44 UTC, mezarque commented on arcadia_pycolor/mpl.py
> +    for fontpath in font_manager.findSystemFonts(fontpaths=font_folder, fontext="ttf"):
I added some text in the docstring to perhaps make this more clear.

2024-06-03 21:47 UTC, mezarque commented on arcadia_pycolor/mpl.py
> +SAVE_WEB = dict(dpi=72, bbox_inches="tight", pad_inches=0.41)
Great, thanks for all these suggestions!

2024-06-03 21:58 UTC, mezarque commented on arcadia_pycolor/style_defaults.py
> +    "half_s": HALF_S,
I feel like fully writing-out `threequarters` is too much, but I expanded the W and S. Ultimately we should make sure that the style guide's terminology for sizing matches with the terminology used here. I'd advocate for something clearer than "full", "three-quarters", and "half" as sizes, because it begs the question "relative to what?" Probably something simple like "small", "medium", "large" and keywords like "tall", "wide", and "square" would be more intuitive.

2024-06-03 22:00 UTC, mezarque commented on arcadia_pycolor/mpl.py
> +            either 'x', 'y', 'both', or None
There may be cases where the categorical axes could be monospaced, e.g. in the case of a sample or strain ID that would be most readable in a monospaced font. So, I think it's fine to allow users to set these on an overlapping basis.

2024-06-03 22:20 UTC, mezarque commented
> What happened to the tests? They seem to have disappeared from the CI workflow.

I'm not sure where you're looking, but at least in my view of the PR, the tests are still running (and if you look at the Actions tab, it seems like they're working still?)

I addressed the remaining comments; lmk if you have any further Qs!

2024-06-03 23:23 UTC, keithchev commented on arcadia_pycolor/style_defaults.py
> +    "half_s": HALF_S,
Agreed. For now, the new names looks clear to me.

2024-06-03 23:25 UTC, keithchev approved these changes
Looks good! 🥳 

(Not sure how I thought the tests went messing, but I see them now.)

2024-06-03 23:39 UTC, merged