Add color vision deficiency, gradient, and palette display tools
Arcadia-Science/arcadia-pycolor pull request #20
Opened 2024-06-07 23:44 UTC by mezarque

## PR checklist

- [x] Tag the issue(s) or milestones this PR fixes (e.g. `Fixes #123, Resolves #456`).
- [x] Describe the changes you've made.
- [x] Describe any tests you have conducted to confirm that your changes behave as expected.

## Overview

This PR adds functionality for simulating color vision deficiency under the `cvd` module.
- addresses #15, enabling simulation of cvd in deuteranomaly, protanomaly, and tritanomaly spaces.
- includes a variety of methods for visualizing color vision deficiency of colors (as `HexCode` objects), palettes, and gradients under `cvd.simulate_color`, `cvd.simulate_palette`, and `cvd.simulate_gradient`. These methods return a transformed version of the color.
- includes a variety of methods for quickly displaying the original color + transformed colors under `cvd.simulate_color_all`, `cvd_simulate_palette_all`, and `cvd.simulate_gradient_all`. These methods return `None` but display all 4 color spaces (normal, d, p, and t).
- includes `cvd.simulate_gradient_lightness()` to display gradient lightness for all three major types of color vision deficiency.

In addition, this PR adds some helpful utilities to the `Palette` and `Gradient` classes:
- a `swatch()` method for `Palette`, which displays all the colors in the palette as a single strip of swatches prior to the specific color swatches, which has parallel functionality to the `swatch()` method for `Gradient`.
- a `.display_all()` method under each of the `palettes` and `gradients` modules, which displays a summary of all of the available colormaps within each module, as per #16.
- a `reversed()` method for `Gradient`s, as per #17.
- automatic registration of reversed gradients into `matplotlib`'s list of color gradients, with the suffix `_r`, as is conventional for `matplotlib`
- a `resample()` method for `Gradient`s, which returns a `Palette` with a resampled list of colors from the original `Gradient`, allowing users to use `Gradient` colors for a categorical plotting purpose, as requested in #4.

## Testing

I confirmed that these functions work using `usage_example.ipynb`, where you can also see how these methods are meant to be used.

## Halp

Would love feedback on the naming and structure of things! I think we can be generally afford to be more verbose / less intuitive with some of the `cvd` stuff, since it's meant to be used primarily by color-obsessives like myself and Audrey.

2024-06-10 22:51 UTC, keithchev requested changes
I did a first pass. Looks pretty good; just the usual comments about naming and clarity. 

Some general comments:
- some nomenclature in `cvd` feels confusing:
    - the names `simulate_color`, `simulate_color_all`, and `simulate_colors` are all very similar. I made some suggestions in inline comments about this, but one way or another, I think it's something we'd want to make a bit clearer (even if these are primarily meant for power users). In particular, I would make sure the names distinguish between methods that return simulated colors and methods that print/display simulated colors.
    - For the color deficiencies, I would favor a more specific name than `form` like `cvd_type`.
- the docstrings of `simulate_palette` and `simulate_palette_all` are duplicated, as are the docstrings for `simulate_gradient` and `simulate_gradient_all`.
- In the `cvd` module, I would make the `cvd_types` dict a global and use it to instead of repeating the hard-coded list of `['d', 'p', 't']` in the subsequent methods.
- should `Palette` also have a `reverse` method?

2024-06-10 23:20 UTC, mezarque commented on arcadia_pycolor/cvd.py
> +    cvd_rgb_color = np.clip(cvd_rgb_color / 255, 0, 1)
Yeah, I can collapse them, I think I was getting confused by the different numerical ranges of colors (RGB1 vs RGB255).

2024-06-10 23:39 UTC, mezarque commented on arcadia_pycolor/cvd.py
> +def simulate_color(color: HexCode, form="d", severity=100) -> HexCode:
It feels a little redundant to add the `_deficiency` on the end when this is already within the `apc.cvd` module, given that `cvd` stands for `color vision deficiency`.

Is `apc.cvd.simulate_color_deficiency(color)` much better than `apc.cvd_simulate_color(color)`?

2024-06-10 23:44 UTC, mezarque commented on arcadia_pycolor/gradient.py
> +            new_values = rescale_and_concatenate_values(self.values, other.values)
Nice, thanks!

2024-06-10 23:48 UTC, mezarque commented on arcadia_pycolor/gradients.py
> +        print(gradient.swatch())
I think because of the inheritance pattern (`gradient` inherits from both `display` and `utils`), this would most simply live in `plot`. 

One question: how can I obtain `_all_gradients` without having to declare each item manually?

2024-06-11 01:08 UTC, keithchev commented on arcadia_pycolor/gradients.py
> +        print(gradient.swatch())
You could leave `_all_gradients` as-is and import it in from `apc.gradients` in `plot`. Or do you mean how would you construct `all_gradients` dynamically? I think that would unfortunately have to be s/t like
```py
all_gradients = [
    object for object in apc.gradients.__dict__.values()
    if isinstance(object, apc.gradient.Gradient)
]
```

2024-06-11 01:14 UTC, keithchev commented on arcadia_pycolor/cvd.py
> +def simulate_color(color: HexCode, form="d", severity=100) -> HexCode:
Yeah, fair. I didn't think about the `cvd` namespace. So `simulate_color` could be fine. I do feel it's important to distinguish between simulating a color and displaying the simulated colors (i.e. between `simulate_color` and `simulate_color_all`).

Also, fwiw I would say `apc.cvd.simulate_color_deficiency` *is* better than `apc.cvd_simulate_color` because the former is namespaced under `cvd` and has a clearer name (in the latter, it's not clear what the `cvd_` prefix is referring to - it could be the simulation, the color, or s/t else).

2024-06-11 14:04 UTC, mertcelebi requested changes
Very close, a couple suggestions + changes

2024-06-11 14:04 UTC, mertcelebi commented on arcadia_pycolor/palette.py
> +            name=f"{self.name}_r",
same here

2024-06-11 14:04 UTC, mertcelebi commented on arcadia_pycolor/utils.py
> +    x0 = 0
These are always set to 0 and 1? I guess it's okay to keep it as the slope calculation and not simplified as `m = y1 - y0`?

2024-06-11 18:45 UTC, mezarque commented on arcadia_pycolor/gradient.py
> +            name=f"{self.name}_r",
Here, I'm trying to conform with `matplotlib`'s [syntax for designating reverse gradients](https://matplotlib.org/stable/gallery/color/colormap_reference.html#reverse-cmap). So, I think we should keep this in place.

2024-06-11 18:46 UTC, mezarque commented on arcadia_pycolor/utils.py
> +    x0 = 0
Hmm good question; I think since we're using mathematical abbreviations, it might be helpful to leave the variables in, even if they're not actually calculating anything, so that future readers will understand the context in which these variables were used.

2024-06-11 18:48 UTC, mezarque commented on arcadia_pycolor/cvd.py
> +    cvd_colors = [colors] + [
Fixed!

2024-06-11 18:53 UTC, mezarque commented on arcadia_pycolor/cvd.py
> +    for cvd_color in cvd_colors:
I think it doesn't ultimately make sense for this function to support multiple colors, since that's the point of `simulate_palette_deficiency`, so I'm updating this to expect a single HexCode as input.

2024-06-11 18:54 UTC, mezarque commented on arcadia_pycolor/cvd.py
> +    for cvd_color in cvd_colors:
Also, `simulate_color_deficiency` updates the color's name, which is displayed as part of the swatch, so it's clear which color space each object is in. e.g. `aegean_t` will represent tritanopia, whereas `aegean` is just the normal color.

2024-06-11 18:55 UTC, mezarque commented on arcadia_pycolor/gradients.py
> +        print(gradient.swatch())
I'll try this! I'm fine to leave `all_gradients` in `gradients` and import it.

2024-06-11 19:05 UTC, mezarque commented on arcadia_pycolor/cvd.py
> +def simulate_color(color: HexCode, form="d", severity=100) -> HexCode:
Ok; I'll revert to remove the `deficiency` suffix from these functions, but keep the `simulate` vs. `display` prefix to make sure that things are clear!

2024-06-11 19:40 UTC, keithchev commented on arcadia_pycolor/utils.py
> +    x0 = 0
Agreed, fwiw. I feel the non-simplified form is clearer.

2024-06-13 19:26 UTC, keithchev approved these changes

2024-06-13 19:38 UTC, merged