Add map_values to Gradient
Arcadia-Science/arcadia-pycolor pull request #43
Opened 2024-07-16 20:39 UTC by ekiefl

# Add map_values method to Gradient

Proposed solution to https://github.com/Arcadia-Science/arcadia-pycolor/issues/41

Something that gave me pause: on one hand I want to "buy in" to the existing data structures and make the return type `list[HexCode]`, but on the other hand I feel it's more practical to return the hex strings since I suspect any callers of this function are typically using it as a final step in their process with the library. I'm curious what you think @mezarque.

2024-07-16 22:03 UTC, keithchev reviewed
Just driving by and thought I'd drop some comments (I'll leave this for @mezarque to approve since it's related to the public-facing API).

2024-07-16 22:03 UTC, keithchev commented on arcadia_pycolor/gradient.py
> +    def map_values(
I think for consistency it would be good to have this method return `list[HexCode]`, since `HexCode` is intended to be how this package always represents strings-that-are-hex-codes. Also, because `HexCode` is a subclass of `str`, I don't *think* this would have any effect on users/calling functions.

2024-07-16 22:07 UTC, mezarque requested changes
Thanks for implementing this! Took a look and left some suggestions.

2024-07-16 22:07 UTC, mezarque commented on arcadia_pycolor/gradient.py
> +        clamped_values = [max(0.0, min(1.0, value)) for value in normalized_values]
I wonder if we should warn the user when values outside of the min/max range are provided, rather than clamping those values silently here.

2024-07-16 22:07 UTC, mezarque commented on arcadia_pycolor/gradient.py
> +                Values less than this are given this color. If not provided, min(values) is
Phrasing feels a bit awkward. Maybe "Values below the minimum are assigned to the minimum color"?

2024-07-16 22:08 UTC, mezarque commented on arcadia_pycolor/gradient.py
> +        if min_value == max_value:
+1

2024-07-16 22:52 UTC, ekiefl commented on arcadia_pycolor/gradient.py
> +    ) -> list[str]:
I agree. To be honest, my reservation to returning `HexCode` stemmed from me not understanding what the string value was. For some reason I thought the string value of `apc.aegean` was `aegean`, not its hex code. I'm happy I was wrong because this makes much more sense both inside and outside of apc land.

Added in 566b705389626922ce6260cc2451564e1705dee8, however I had to make a decision about the HexCode name that I'd like your feedback on.

![image](https://github.com/user-attachments/assets/baf95bd1-6ef8-4256-b21c-9f42052459a0)

Personally, I like that the values are accessible, though it is abusing the name attribute to be sure.

2024-07-16 22:54 UTC, ekiefl commented on arcadia_pycolor/gradient.py
> +    def map_values(
566b705389626922ce6260cc2451564e1705dee8

See https://github.com/Arcadia-Science/arcadia-pycolor/pull/43#discussion_r1680145395

2024-07-16 22:57 UTC, ekiefl commented on arcadia_pycolor/gradient.py
> +        if min_value == max_value:
👍 8328e6781d6cc92eef33ff465c33887c4cce4d08

2024-07-16 22:58 UTC, ekiefl commented on arcadia_pycolor/tests/test_gradients.py
> +def test_map_values_basic_cases(
c3edb8285493da686dd1d1bde031223be4e09838

2024-07-16 22:58 UTC, ekiefl commented on arcadia_pycolor/gradient.py
> +        clamped_values = [max(0.0, min(1.0, value)) for value in normalized_values]
I can only speak to my personal usage with colormaps, but if I'm touching the min and max values, it's usually because I'm interested in the middle of the color range, but far-reaching extrema values are decreasing contrast.

Like if your data is spread like this (each `x` a datapoint, each `|` the min/max value):

```bash
x                           x x    x x  x x x x x x x x                              x
|                                                                                    |
red                                  yellow                                      green
```

The bulk of the data is washed out. In comparison, by setting min/max inside the value range:

```bash
x                           x x    x x  x x x x x x x x                              x
                          |                             |
red                       red          yellow       green                        green
```

You get more contrast in the region you care about.

All this is to say that I personally would not want a warning that I'm doing this, because it would be very intentional.

2024-07-16 23:01 UTC, ekiefl commented on arcadia_pycolor/gradient.py
> +                Values less than this are given this color. If not provided, min(values) is
9f0c6110aec7960bad39a4f65b327542de394db5

2024-07-17 01:41 UTC, mezarque commented on arcadia_pycolor/gradient.py
> +    ) -> list[str]:
I think this is fine; we make a similar kind of assignment when using `apc.gradients.resample_as_palette()`. I do feel like rounding the values to a fixed number of digits would be more legible, but I suppose that's not ideal if you want to be able to exactly assign a color to a value.

2024-07-17 01:46 UTC, mezarque commented on arcadia_pycolor/gradient.py
> +        clamped_values = [max(0.0, min(1.0, value)) for value in normalized_values]
I understand this use case a bit better, thanks! I do wonder if it would be good to use the `matplotlib` [`set_extremes`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.Colormap.html#matplotlib.colors.Colormap.set_extremes) functionality when windowing the data in this way, so that colors over and under the gradient are distinctly marked as out of range. Probably not relevant to your structure viewer use case, but in a heatmap or other context, it would be important to indicate so as to avoid misleading readers.

2024-07-17 01:50 UTC, mezarque approved these changes
Looks good to me! Thanks for addressing those comments.

Before merging, I do wonder if we should get a sense of how often we want to cut new releases on GitHub and distributions to PyPI. @keithchev any thoughts? I imagine it would make Evan's life a little easier if this is included in the PyPI-distributed version, but we should be disciplined about what amount of change necessitates a minor or patch version bump.

2024-07-17 15:23 UTC, keithchev commented
> Before merging, I do wonder if we should get a sense of how often we want to cut new releases on GitHub and distributions to PyPI. @keithchev any thoughts? I imagine it would make Evan's life a little easier if this is included in the PyPI-distributed version, but we should be disciplined about what amount of change necessitates a minor or patch version bump.

Yeah, if we end up with like version `0.5.200` we're probably doing something wrong. And of course we want to be disciplined about releasing breaking changes. But I think we can err on the side of leniency for minor versions for now, at least for new features like this one that may unblock or facilitate a user's work.

2024-07-17 16:18 UTC, mezarque commented
Sounds good! Feel free to merge @ekiefl. @keithchev would you mind distributing to PyPI?

2024-07-17 17:05 UTC, ekiefl commented on arcadia_pycolor/gradient.py
> +        clamped_values = [max(0.0, min(1.0, value)) for value in normalized_values]
Yeah good idea. By name, I thought that `set_extremes` would allow us to avoid normalizing the data altogether, by setting the extrema for the value range. But looking into the implementation, I now see it allows you to control the colors of those outside 0 to 1.

This could be useful if we wanted more fancy features and could be accomplished by propagating those args to the `map_values` call signature.

Either way, it's noteworthy that the default behavior for `over` and `under` is to clamp the color to the lowest/highest color. Here's a black to white cmap:

```
(Pdb) mcolors.to_hex(cmap(-1.0))
'#000000'
(Pdb) mcolors.to_hex(cmap(2.0))
'#ffffff'
```

That's what we we were manually doing. As a step towards implementing `over`/`under`/`bad`, the clamping op has been removed (0c1c8af9cc3530276271874484599f8c28c03480).

2024-07-17 17:06 UTC, ekiefl commented
Merging now. Made a small change described here: https://github.com/Arcadia-Science/arcadia-pycolor/pull/43#discussion_r1681397776

2024-07-17 17:22 UTC, merged