Start of rebuilding the package
Arcadia-Science/arcadia-pycolor pull request #8
Opened 2024-05-17 22:05 UTC by mezarque

## PR checklist

- [x] Describe the changes you've made.
- [x] Describe any tests you have conducted to confirm that your changes behave as expected.
- [x] If you've added new software dependencies, make sure that those dependencies are included in the appropriate `conda` environments.

# Overview
This PR begins the process of reworking this repository into a more robust Python package. As part of this, I'm going to refactor the core classes, starting with the Palette class and the new Color class. I'm temporarily adding a "_new" suffix to any modules that will eventually replace old modules and will gradually migrate as much necessary functionality from those old modules as possible into a new, more principled organization.

## Design Choices
Keith and I chatted a bit offline about some high- and low-level design choices for this package. We agreed that:
- Compartmentalizing different functions into separate modules would be ideal (e.g. `matplotlib`-related functions should live in their own module.)
- To transition to the new way of doing things, I'll mostly rebuild functionality from scratch, rather than modifying the existing repo.
- We might make exceptions to the above to streamline usability for special cases. For example, rather than storing the individual colors in a `colors` module and having users type `apc.colors.aegean`, we settled on having those colors live in the highest level of the namespace, e.g. as `apc.aegean`.

## Changes
- Introduce an updated `Palette` class with reduced functionality (for now).
- Introduce a new `Color` class that allows users to see colors more easily, which are collected into `Palette` objects.
- Re-factor the existing `colors.py` collection of constants using `colors_new.py`; Gradients are yet to be implemented.
- Add a `display.py` module that will be used to collect all color display functions.
- No new dependencies.

## Testing
- You can see the functionality behaving as expected in the `usage_example.ipynb` notebook.

## Questions
- Currently, `Color` inherits from `str` so that it can be properly handled as a HEX code string by downstream libraries (e.g. `matplotlib`, `seaborn`, `plotly`). This works and has a better UX than having to call a method to get the HEX code, but I'm not sure if it's a good idea.
- Should we be using `pydantic` or something to have easier validation of input types? I tried implementing this, but the `Color` `str` inheritance made it tricky to figure out, so I abandoned it.
- Palettes are currently stored at the highest level of the namespace using `ALLCAPS` variable names. What's the preferred way to store them? Should they be in their own module? What should our naming convention be?
- What should the naming convention be for colors? I think the `apc.lowercase` UX is the simplest, but does it go against the expectation that constants are in `ALLCAPS`?
- What tests should we write for this package? I'm happy to do it, but it will take some time for me to get up to speed.

## Next
After this PR, I'll start working on:
- [ ] Implementing the `Gradient` class.
- [ ] Adding in methods to allow users to display `Gradient` colors.
Then, I'll put together:
- [ ] A module for styling `matplotlib` plots with style sheets and various helper functions.

2024-05-17 23:44 UTC, mezarque commented
Something fun about the way that `__repr()__` is now implemented is that you can see colors even when running an interactive Python session in the terminal.

![Screenshot 2024-05-17 at 4 42 54 PM](https://github.com/Arcadia-Science/arcadia-pycolor/assets/6531296/f0d69cc7-5da5-4bc1-9f2b-0c646c9e4bef)

2024-05-20 21:26 UTC, keithchev requested changes
This looks like a great start! I love the swatches and it's so cool that they work basically everywhere.

I made an initial round of comments, mostly about implementation. For context, I'm trying to apply a pretty high bar to the code, since we're imagining that this will become a long-lived project and a dependency of many other projects at Arcadia.

My takes on the questions from the PR description:

> * Currently, `Color` inherits from `str` so that it can be properly handled as a HEX code string by downstream libraries (e.g. `matplotlib`, `seaborn`, `plotly`). This works and has a better UX than having to call a method to get the HEX code, but I'm not sure if it's a good idea.

I commented in detail on this in an inline comment, but TLDR, I don't think it's a good idea.

> * Should we be using `pydantic` or something to have easier validation of input types? I tried implementing this, but the `Color` `str` inheritance made it tricky to figure out, so I abandoned it.

For relatively simple validation (e.g. of a hex code), pydantic probably isn't worth it, imo. I would say we can make a note to revisit this later on, especially if we find that writing validation logic is becoming cumbersome. 

> * Palettes are currently stored at the highest level of the namespace using `ALLCAPS` variable names. What's the preferred way to store them? Should they be in their own module? What should our naming convention be?

I think they should be defined in their own module `palettes.py` and namespaced under `apc.palettes` so that they are clearly separated from the colors. And I think all-lowercase names are fine (see below).

> * What should the naming convention be for colors? I think the `apc.lowercase` UX is the simplest, but does it go against the expectation that constants are in `ALLCAPS`?

I think lowercase is okay, even though it breaks with convention since the `Color` instances are technically constants. This feels like a gray area to me because the `colors` module contains nothing but color definitions, so the colors (and palettes) "feel" closer to class attributes (where the "class" is actually a module) than constants. Also, practically, it means there's not a need to distinguish between constants and functions (this would be even more true if colors were namespaces under `apc.colors`, but I think lowercase is okay even if they're not).

> * What tests should we write for this package? I'm happy to do it, but it will take some time for me to get up to speed.

I would say that tests for input validation would probably be the most important, since those deal with user-provided values that could be weird. And then tests for conversion methods like hex-to-rgb, since those are so fundamental. But I think this package is simple enough that we can afford to wait on this for a little while until we have a stable-ish public API, and then we can go back add tests (also happy to do this and/or help!)

2024-05-20 21:34 UTC, mezarque commented on arcadia_pycolor/colors_new.py
> +k = Color("k", "#000000")
This is fair; one problem is that Arcadia's color palette already has a `black` entry that is not `#000000`. So we'd need to rename that `black` to something else. But I think that was the main reason I used these abbreviations.

2024-05-20 21:49 UTC, mezarque commented on arcadia_pycolor/classes_new.py
> +class Color(str):
I think this makes sense to me overall from a software perspective, but it does make the user experience somewhat more annoying; needing to type `.hex_code` after every instance of a color usage feels like it will get wordy over time. For example, between `apc.tangerine` and `apc.tangerine.hex_code`, the latter feels pretty ugly/ unwieldy. I've updated this so that the `str` inheritance is removed, but given that direct access to colors will likely be one of the most-used features, I wonder if we can figure out some way to get the `apc.tangerine` syntax to work properly without inheriting from `str`.

2024-05-20 21:54 UTC, mezarque commented on arcadia_pycolor/colors_new.py
> +CORE = Palette(
How should I deal with importing the colors? If I don't use * import, will I have to list all of the color names?

2024-05-20 21:56 UTC, mezarque commented on arcadia_pycolor/colors_new.py
> +k = Color("k", "#000000")
I'm going to rename the existing `black` to `pitch` and go with the fully spelled-out names.

2024-05-20 22:31 UTC, keithchev commented
Two more comments I forgot to include:
- it looks like the env files are out of date. `dev.yml` looks like it might have been inherited from the python template, since it has nothing specific to this repo, and `apc.yml` uses python 3.9, but the type hints require python 3.12. I figured I should mention this but I don't know if it's worth dealing with this now, since the deps will have to be moved into `pyproject.toml` anyway to make the package pip-installable. 
- since we're breaking the transition between "old" and "revamped" versions of the package into multiple PRs, it would be a good practice to merge PRs to a branch other than `main`, so no one uses the package in its current in-between state (this isn't a huge deal since the "old" package is still usable; it's more of a best practice that errs on the side of caution).

2024-05-20 22:42 UTC, mertcelebi reviewed
Keith already gave a pretty thorough review, so leaving some comments/questions. 

One note I have is around modules. I think having all the colors be namespaced under `apc.colors` and palettes under `apc.palettes`. Yes, it's longer to type, but feels more natural/logical to me.

2024-05-20 22:42 UTC, mertcelebi commented on arcadia_pycolor/__init__.py
> +from .classes_new import *
Why do we have to name these like that? I'd prefer to name these as `classes` and name the old ones as `classes_old`. 

If it's to avoid weird version issues with installed instances of `arcadia-pycolor`. It may be a good idea to merge these changes to a feature branch other than main. And when we're ready to merge to main, we can go from feature branch to main.

2024-05-20 22:42 UTC, mertcelebi commented on pyproject.toml
> +"usage_example.ipynb" = ["B018", "E402"]
See this thread: https://arcadiascience.slack.com/archives/C04AKK76CDN/p1716233305279529

I think we should update the ruff version of the repo and not explicitly ignore these "rules"

2024-05-20 22:42 UTC, mertcelebi commented on arcadia_pycolor/classes_new.py
> +        longest_name = max(len(color.name) for color in self.colors.values())
Given the definition of colors is a "dict or a list", this should handle different types

2024-05-20 22:42 UTC, mertcelebi commented on arcadia_pycolor/classes_new.py
> +    def __repr__(self):
I am by no means a Python expert, so excuse my naive question but this seems a little unconventional to me. I would have expected `__repr__` to be a debug friendly version of the class so it can be re-instantiated, and `__str__` to be more like this. Am I wrong?

2024-05-20 22:42 UTC, mertcelebi commented on arcadia_pycolor/classes_new.py
> +        self.colors = [Color(name, hex_code) for name, hex_code in colors.items()]
The below comment applies to this as well

2024-05-20 22:46 UTC, mertcelebi commented on arcadia_pycolor/classes_new.py
> +    def __repr__(self):
While at it, could you also explain what this means?

"Currently, Color inherits from str so that it can be properly handled as a HEX code string by downstream libraries (e.g. matplotlib, seaborn, plotly). This works and has a better UX than having to call a method to get the HEX code, but I'm not sure if it's a good idea."

Does it mean, when `Color` inherited from `str`, you could pass it to these downstream tools directly with `apc.blah` and now you need to do `apc.blah.hex_code`?

2024-05-21 00:01 UTC, keithchev commented on arcadia_pycolor/classes_new.py
> +    def __repr__(self):
> I am by no means a Python expert, so excuse my naive question but this seems a little unconventional to me. I would have expected `__repr__` to be a debug friendly version of the class so it can be re-instantiated, and `__str__` to be more like this. Am I wrong?

FWIW my take on this is that returning a color swatch adheres to the *spirit* of the `__repr__` method, which I'm interpreting to be that it should return a succinct representation of the object that is useful for debugging. In this special case of color, the argument would be that the swatch is more meaningful and interpretable than something like `Color(hex_code="#fff")` for most users. There is some precedent for this with e.g. pandas dataframes, whose `__repr__` method returns a truncated and pretty-printed dataframe rather than `pd.DataFrame(data=...)`.

2024-05-21 00:08 UTC, keithchev commented on arcadia_pycolor/classes_new.py
> +    def __repr__(self):
There are also two pragmatic considerations: 
- `__repr__` is what is called by jupyter notebooks to evaluate expressions, so I think it's the only way to show the swatch when the user types a color like `apc.tangerine` in a notebook cell.
- if we want `str(color)` to return the hex code, we have to reserve `__str__` for returning the hex code itself.

2024-05-21 17:37 UTC, keithchev commented
@mezarque I chatted with Mert briefly about the subclassing-str thing, and we had an idea that we think would be user-friendly and also avoid the weirdness of a `Color` class that subclasses `str`. The idea is to avoid the need to define a `Color` class entirely by defining utility functions for color operations like `lighten` and `darken` etc. We thought this would still be ergonomic/intuitive since the user would write `lighten(apc.tangerine)` rather than `apc.tangerine.lighten()`. And of course we could define the colors themselves as instances of a `HexCode` class that inherits from string (as we discussed yesterday) so `apc.tangerine` could be passed directly to matplotlib plots etc.

2024-05-21 18:18 UTC, mezarque commented on arcadia_pycolor/__init__.py
> +from .classes_new import *
I agree that we should be merging into a feature branch rather than main; I'm going to address PR comments here until we're satisfied, then close this PR and open a fresh one to a feature branch.

2024-05-21 18:20 UTC, mezarque commented on arcadia_pycolor/classes_new.py
> +        longest_name = max(len(color.name) for color in self.colors.values())
We decided to just have `self.colors` be a list, so I've refactored for that constraint.

2024-05-21 18:22 UTC, mezarque commented on arcadia_pycolor/classes_new.py
> +    def __repr__(self):
Ditto all of what Keith said above! In general I am trying to aim for the best usability, and am willing to advocate for some sacrifices in the purity of the architecture if it means we can make the package really clear and simple for downstream users.

2024-05-21 19:16 UTC, mezarque commented
Thanks for all your feedback! I'm learning a lot.
I made a variety of changes as suggested:

- There is now a `palettes` module.
- The `Color` class is now `HexCode` and inherits from `str`, replacing its `__repr__` so we can see color swatches.
- Renamed old code to have `_old` suffix.
- The `Palette` class now by default accepts a list of `HexCode` objects. To instantiate from a `dict` of `str`, there's now the `from_dict()` classmethod.

Some remaining points of discussion:
- I haven't removed the `to_rgb` method from `HexCode`. It doesn't feel that unnatural to me to keep it there.
- I have kept all the colors within the high-level namespace, e.g. they're accessed as `apc.aegean` rather than `apc.colors.aegean`. I am pretty resolute in wanting to keep that structure, because I expect users will be accessing colors a great deal.

If this sounds OK, I'm going to close this PR and open a new one on a feature branch so we avoid breaking everything in main.

2024-05-22 01:27 UTC, keithchev approved these changes
Looks good! Thanks for your patience with my engineering-y-ness 😄 

Agree that `to_rgb` feels okay on `HexCode`. But I feel we should draw the line at methods like `lighten` and `darken` since (as we discussed) that opens the door to a large number of color-specific methods and potential confusion.

Aside: I noticed the swatches for very light colors need some work, since they're invisible if the background is white (e.g. a jupyter notebook in light mode). And I guess the opposite will be true in dark mode. But something for a future PR.

> If this sounds OK, I'm going to close this PR and open a new one on a feature branch so we avoid breaking everything in main.

I think there should be a way to avoid doing this (which would be preferable to preserve the history): create a new branch at `main`, push it to the remote, then change the "base" of this PR to that new branch (by clicking the "edit" button next to the PR title).

2024-05-22 02:55 UTC, merged