New implementation of gradients
Arcadia-Science/arcadia-pycolor pull request #9
Opened 2024-05-22 19:21 UTC by mezarque

## PR checklist

- [x] Describe the changes you've made.
- [x] Describe any tests you have conducted to confirm that your changes behave as expected.

## Overview

This PR introduces a reworked `Gradient` subclass, which inherits from the `Palette` class. The main difference is that the `Gradient` subclass also has a list of positions associated with each color, on a scale from 0 to 1, which describe the gradient.

## Changes
- Fixed some color names (e.g. `b` -> `black`)
- Added `Gradient` subclass.
- Added `gradient_swatch` display utility, which creates a special swatch that shows a range of gradient steps as part of the `__repr__` for the `Gradient` class.
- Added `plot_gradient_lightness` display utility, which converts a gradient to HSL colorspace and plots lightness; useful when creating new gradients. I expect this to be used almost exclusively by myself and Audrey, but it's something she really wanted access to.
- Added an `mpl` module with `to_cmap` and `to_linear_cmap` methods that create `matplotlib`-relevant objects that are useful for interpolating gradients (and which will be used to load colors, gradients, and palettes into `matplotlib` in the future).
- Define the same gradients that were available in the previous version in the `gradients` module. These may change again in the future, as Audrey is looking into what the right options are, but I wanted to put these in for now.

## Questions
- In the `gradient_swatch` method, I import `HexCode` locally to avoid a circular dependency error. The `if TYPE_CHECKING` statement alone results in an error because `HexCode` is undefined. How do I resolve this? Should the first parts of the `gradient_swatch` method live somewhere else?

## Next
Before adding in functionality for `matplotlib`, which I've already figured out, I wonder if it would be good to put some testing in place. I know Keith can do this, but I would also like to learn some testing basics. What are some good tests to write for the package as it is now?

2024-05-22 19:28 UTC, mezarque commented on arcadia_pycolor/display.py
> +    gradients: Union["Gradient", str, list[Union["Gradient", str]]],
I realize this is kind of a mess, but I don't want to force the user to unintuitively wrap a single gradient entry in a list in order for this function to work. What's the best way to do that?

2024-05-22 19:29 UTC, mezarque commented on arcadia_pycolor/display.py
> +    from arcadia_pycolor.classes import HexCode
Is this fine? I can't import at the top because of a circular dependency error, and the `if TYPE_CHECKING` alone doesn't actually allow `HexCode` to be in the namespace, which results in an undefined error.

2024-05-23 18:25 UTC, keithchev requested changes
Looks good! TLDR the nested import statements should be avoided if possible. I made some suggestions about this in inline comments.

One important thing: it looks like the `apc.utils` module is missing from the PR.

A few minor things:
- the `__all__` in the top-level `__init__.py` needs to be updated.
- consider renaming `swatch` to `color_swatch` for symmetry with `gradient_swatch` and adding a verb to the name like `make_color_swatch` to clarify that it's a function and not a variable.
- there are some missing type hints, particularly for return types. This is nbd for now, imo, as we can always go back and add them later.

Ideas for tests:
- tests for the low-level utility functions like `colorize` and `swatch`. Make sure they behave as expected for some hard-coded colors and don't work for some common kinds of invalid input (`None`, empty string, a string like `"red"`, an invalid hex code, etc). 
- tests for the core primitives (`HexCode`, `Palette`, `Gradient`). Instantiate them with hard-coded valid and invalid input both directly and using `from_dict`. Check that `__repr__` functions return the expected output, since that's an important part of the user-facing functionality. Check that two palettes can be added together, check that gradient-to-cmap conversion works as expected, etc.

2024-05-23 18:25 UTC, keithchev commented on arcadia_pycolor/display.py
> +    from arcadia_pycolor.classes import HexCode
Yeah, this should be avoided. I think in this case the circular import is a sign that things could be reorganized. There are two options that I think could work:
1) move `gradient_swatch` to a method of `Gradient` (it could be a static method if needed). For consistency I'd also move `to_linear_cmap`.
2) define `colorize` to accept a hex code as a `str` (so you don't need to import `HexCode` here). Since it seems like `colorize` is an internal utility and not part of the public API, this feels fine to me.

I think either would be fine but I'd vote for option (1) since it helps keep things a bit more organized, especially as it looks like `gradient_swatch` is intended for use in `Gradient.__repr__`, in which case it is properly a private instance method of `Gradient`.

2024-05-23 18:25 UTC, keithchev commented on arcadia_pycolor/display.py
> +    from arcadia_pycolor.classes import Gradient
This nested import should also ideally be avoided. One way would be to move the plotting function out of this module and into something like `plotting`, which would separate it from `colorize` (which feels like a utility).

2024-05-23 19:46 UTC, mezarque commented on arcadia_pycolor/__init__.py
> +from .mpl import *
Makes sense!

2024-05-23 19:48 UTC, mezarque commented on arcadia_pycolor/display.py
> +        return fig
This is made available so that a user can save, annotate, or otherwise modify the figure if they'd like to. For example, `plt.savefig()` must be called before `plt.show()`. Probably won't be used by most folks, but it's good to have the option (and saves them from having to reproduce this plotting code just to be able to handle the figure).

2024-05-23 19:50 UTC, mezarque commented on arcadia_pycolor/display.py
> +        lab = cspace_converter("sRGB1", "CAM02-UCS")(rgb)
This is great; thanks for untangling this! I was modifying some old code and it was simpler just to add more conditionals, but certainly not elegant.

2024-05-23 19:53 UTC, mezarque commented on arcadia_pycolor/display.py
> +    gradients: Union["Gradient", str, list[Union["Gradient", str]]],
For some reason my Python 3.12 is throwing invalid operator errors with `|`, so I just used `Union` to get around that. Not sure what's going on, but we can revisit once I've figured out what's going on with my machine/ Python kernel. `Union` might also enable us to support older Python versions that don't support the `|` operator.

2024-05-23 19:53 UTC, mezarque commented on arcadia_pycolor/display.py
> +def plot_gradient_lightness(
In this case, the plotting works both for a singular and a plural number of gradients, so I think the non-plural form makes more sense.

2024-05-23 19:56 UTC, mezarque commented on arcadia_pycolor/display.py
> +    from arcadia_pycolor.classes import HexCode
Should I also move `to_cmap()` to `Palette` then? My only concern there is that this mixes the `matplotlib`-specific functionality into the class. Given that we'd eventually like this to work with `plotly`, for example, a generic `to_cmap` method of `Palette` or `Gradient` would probably be confusing. We could get around this by having methods like `to_mpl_linear_cmap()`, but that feels kind of verbose.

2024-05-23 20:00 UTC, mezarque commented on arcadia_pycolor/gradients.py
> +poppies = Gradient(
I wonder about the ergonomics of writing out these names actually; maybe an abbreviation scheme like `matplotlib` uses would be reasonable?

e.g. see [here](https://matplotlib.org/stable/users/explain/colors/colormaps.html)

2024-05-23 20:21 UTC, mezarque commented on arcadia_pycolor/display.py
> +    from arcadia_pycolor.classes import Gradient
I ended up moving both `swatch()` and `gradient_swatch()` into class methods of `Color` and `Gradient` respectively. They're both called via `swatch()` now, because imo it would feel silly to call `.gradient_swatch()` on something you already know to be a gradient.

2024-05-23 20:36 UTC, keithchev commented on arcadia_pycolor/display.py
> +    from arcadia_pycolor.classes import HexCode
I meannn, I kinda like the `to_mpl_linear_cmap` idea. But because `to_cmap` converts to a matplotlib-specific object, I think it would also make sense to leave it in `mpl`.

2024-05-23 20:37 UTC, keithchev commented on arcadia_pycolor/display.py
> +def plot_gradient_lightness(
Mmm I see. Fair enough!

2024-05-23 20:40 UTC, keithchev commented on arcadia_pycolor/gradients.py
> +poppies = Gradient(
Yeah, I think the `RdBuGn`-style abbreviations could work, though otoh there are some pretty esoteric color names so the abbreviations could be too opaque. 

Separately, the names like `poppies` would be less ambiguous if the gradients were namespaced under `apc.gradients` so that there could be no mistaking `pac.gradients.poppies` for a color.

2024-05-23 20:42 UTC, keithchev commented on arcadia_pycolor/display.py
> +    from arcadia_pycolor.classes import Gradient
Nice. Agreed; if they're class methods, the name `swatch` alone is fine.

2024-05-23 21:13 UTC, mezarque commented on arcadia_pycolor/gradients.py
> +poppies = Gradient(
I've got them namespaced under `gradients` now so I'm going to revert to the flower names for now; probably the gradients will change soon anyway once Audrey gets back.

2024-05-23 21:21 UTC, mezarque commented on arcadia_pycolor/display.py
> +    from arcadia_pycolor.classes import HexCode
I might move the `to_mpl_linear_cmap()` direction in the future, but let's just keep it in the `mpl` module for now; I think we can revisit once I've added the various utilities that will be included there and we can get a better sense of whether they should be separated out.

2024-05-23 21:37 UTC, mezarque commented
I'm going to try to implement testing in another PR, just to keep things tidier.

2024-05-23 22:07 UTC, keithchev reviewed
Just two more comments (sorry!)

2024-05-23 22:07 UTC, keithchev commented on arcadia_pycolor/utils.py
> +def distribute_values(objects, min_val=0, max_val=1):
Could this function accept a length `num_points` instead of a list `objects`? This would be simpler (and easier to type-hint), since the function does not depend on the contents of the list but just its length.

2024-05-23 22:24 UTC, mezarque commented on arcadia_pycolor/utils.py
> +def distribute_values(objects, min_val=0, max_val=1):
can do!

2024-05-23 22:29 UTC, mezarque commented on arcadia_pycolor/__init__.py
> +]
One wonders if Tiktaalik could have foreseen the wonders of its descendants' lives upon the land...

Thanks for figuring out how to do this, it's implemented now!

2024-05-23 22:44 UTC, mertcelebi reviewed
This looks good to me. Made a couple small comments. I'll let Keith approve when he does a final pass.

2024-05-23 22:44 UTC, mertcelebi commented on arcadia_pycolor/classes.py
> +def _get_longest_name(palette: Palette) -> int:
Is there a reason this is outside the `Palette` class?

2024-05-23 22:44 UTC, mertcelebi commented on arcadia_pycolor/classes.py
> +def _get_longest_name(palette: Palette) -> int:
Or maybe part of a util file?

2024-05-24 17:04 UTC, mezarque commented on arcadia_pycolor/classes.py
> +def _get_longest_name(palette: Palette) -> int:
Inside Palette class feels tidier to me; I've moved it!

2024-05-24 17:08 UTC, mezarque commented
Thanks for all your feedback! I moved `_get_longest_name()` and made associated changes. Merging shortly!

2024-05-24 17:08 UTC, merged